config/routes.rb
Rails.application.routes.draw do

get 'hosts/index' => 'hosts#index'

#   get 'users/index'
#   get 'users/display'
#   get 'users/replace'
#   get 'users/update'
#   get 'users/destroy'

root :to => 'users#index'
# resources :searches
resources :talents do
  collection do
    get :search
  end
end


get '/host' => 'hosts#index'
get '/talent' => 'talents#index'

get '/host_review' => 'host_reviews#index'
get '/talent_review' => 'talent_reviews#index'
get '/talent_list' => 'talents#show'

post '/talent_filter' => 'talents#create'

get '/talent_filter' => 'talents#profile'

post '/talent' => 'talents#show'

get '/talent_create' => 'talents#create'

get 'show' =>'talents#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/host.rb
class Host < ApplicationRecord
    has_many :host_reviews
    has_many :talents
    has_many :talent_reviews
end

app/models/host_review.rb
class HostReview < ApplicationRecord
    belongs_to :host, dependent: :destroy
    
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  validates_presence_of :title

  mount_uploader :image, ImageUploader
end


as talent if you are good at guitar
[
image,
portfolio[videos, clean, reviews],
]
as a host you want  a good guitarist

app/models/talent.rb
class Talent < ApplicationRecord
    has_many :talent_reviews
    belongs_to :host

    def self.search(params)
        if params[:search].present?  
            if params[:state_select].present?
                talents = Talent.where("talent_offered LIKE (?) and location LIKE (?)", "%#{params[:search]}%", "%#{params[:state_select]}%")
            else
                talents = Talent.where("talent_offered LIKE (?)", "%#{params[:search]}%") 
            end       

        else    
            talents = Talent.where("location LIKE (?)", "%#{params[:state_select]}%")
        end
        
    end         
end

app/models/talent_review.rb
class TalentReview < ApplicationRecord
    belongs_to :talent, dependent: :destroy
    belongs_to :host
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SearchHelper
  before_action :search_navdiv

  protected
  def search_navdiv
    @search_navdiv = true
  end

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController

  def index
   @hosts = Host.all.reverse
  end

end

app/controllers/snippets_controller.rb
class Snippets_Controller < ApplicationController

    def snippet_params
        params.require(:snippet).permit(:title, :content, :image)
    end
    
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
skip_before_action :search_navdiv, :only => :profile
# skip_before_action :partial_name, :only => :methodname

  def index
    @talents = Talent.all
  end

  def create
    # @talents = Talent.find(params[:id])
    # redirect_to '/talent_filter'
  end

  def profile
    def snippet_params
        params.require(:snippet).permit(:title, :content, :image)
    end
  end

  def search 
    if params[:search].blank? and params[:state_select].blank?
      @talents = Talent.all
    else
      @talents = Talent.search(params)
      value = params[:search]
    end
  end

  def show
    @talents = Talent.new
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @talents = Talent.all.reverse
  end

  def display
  end

  def replace
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
    def us_states
        [
          ['State',''],  
          ['Alabama', 'AL'],
          ['Alaska', 'AK'],
          ['Arizona', 'AZ'],
          ['Arkansas', 'AR'],
          ['California', 'CA'],
          ['Colorado', 'CO'],
          ['Connecticut', 'CT'],
          ['Delaware', 'DE'],
          ['District of Columbia', 'DC'],
          ['Florida', 'FL'],
          ['Georgia', 'GA'],
          ['Hawaii', 'HI'],
          ['Idaho', 'ID'],
          ['Illinois', 'IL'],
          ['Indiana', 'IN'],
          ['Iowa', 'IA'],
          ['Kansas', 'KS'],
          ['Kentucky', 'KY'],
          ['Louisiana', 'LA'],
          ['Maine', 'ME'],
          ['Maryland', 'MD'],
          ['Massachusetts', 'MA'],
          ['Michigan', 'MI'],
          ['Minnesota', 'MN'],
          ['Mississippi', 'MS'],
          ['Missouri', 'MO'],
          ['Montana', 'MT'],
          ['Nebraska', 'NE'],
          ['Nevada', 'NV'],
          ['New Hampshire', 'NH'],
          ['New Jersey', 'NJ'],
          ['New Mexico', 'NM'],
          ['New York', 'NY'],
          ['North Carolina', 'NC'],
          ['North Dakota', 'ND'],
          ['Ohio', 'OH'],
          ['Oklahoma', 'OK'],
          ['Oregon', 'OR'],
          ['Pennsylvania', 'PA'],
          ['Puerto Rico', 'PR'],
          ['Rhode Island', 'RI'],
          ['South Carolina', 'SC'],
          ['South Dakota', 'SD'],
          ['Tennessee', 'TN'],
          ['Texas', 'TX'],
          ['Utah', 'UT'],
          ['Vermont', 'VT'],
          ['Virginia', 'VA'],
          ['Washington', 'WA'],
          ['West Virginia', 'WV'],
          ['Wisconsin', 'WI'],
          ['Wyoming', 'WY']
        ]
    end

end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hosts/index.html.erb
<h1><%= @hosts.first.user_name %></h1>

<% @hosts.each do |host| %>
    <% host.host_reviews.each do |review| %>
        <p><%= review.reviews %></p>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webisac</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/drawer' %>
  <nav id="my_navigation">
    <div id="nav_left">
    <%= image_tag "ice.png", width:'100px', :id => "logo_image" %>
    <h4 id="company_name">Isaec</h4>
    </div>
    <div id="nav_right">
        <div id="nav_my_account"><div class="account_header"><a id="link_to_account" href="#account">MY ACCOUNT</a></div></div>
        <div id="nav_post_gig"><button class="post_button"><a href="https://rawgit.com/Marak/faker.js/master/examples/browser/js/faker.js">POST AN GIG</a></button></div>
    </div>
  </nav>


  <div id="below_nav_divider" class="ui inverted divider"></div>


  <% if @search_navdiv %>
    <%= render 'shared/search_navdiv', locals: {ser: @ser, state: @state}%>
  <% end %>

  <div id="main_content">
    <div id="yield_content">
        <%= yield %>
    </div>
  </div>
  
  
  <%= render 'shared/these_footer' %>

    <script src = "https://rawgit.com/Marak/faker.js/master/examples/browser/js/faker.js" type = "text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_drawer.html.erb
<div id="navigation_drawer">
    <div id="outside_child_drawer">
        <div id="top_child_drawer"></div>
        <div id="bottom_child_drawer">
            <div id ="vertical_menu" class="ui vertical menu">
                <div class="item">
                    <div class="header">Profile</div>
                    <div class="menu">
                        <a class="item">Enterprise</a>
                        <a class="item">Consumer</a>
                        <a class="item">Supplier</a>
                    </div>
                </div>
                <div class="item">
                    <div class="header">System</div>
                    <div class="menu">
                        <a class="item">Enterprise</a>
                        <a class="item">Consumer</a>
                        <a class="item">Supplier</a>
                    </div>
                </div>
                <div class="item">
                    <div class="header">Products</div>
                    <div class="menu">
                        <a class="item">Enterprise</a>
                        <a class="item">Consumer</a>
                        <a class="item">Supplier</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_search_navdiv.html.erb
<%= form_tag search_talents_path, method: :get do %>
    <div id="search_nav_div">
        <div id="search_div">
            <div id="work_input_div" class="ui inverted left icon input">
                <%= text_field_tag :search, nil, placeholder: "Search", id: "form2", class: "ui form"%>
                <i class="search icon"></i>
            </div>
        </div>
        <div class="search_drop_down">
            <div class="ui container">
                <%= select_tag :state_select, options_for_select(us_states), class: 'ui selection dropdown', id: "state_name" %>
            </div>    
        </div>
        <%= submit_tag "Search", class: "ui button" %>
    </div>    
<% end %> 
<br>

<div id="return_search">
    <%= link_to 'Return Home', talents_path, class:"ui twitter button"%>
</div>

app/views/shared/_these_footer.html.erb
<footer id="classic_footer">
    <div id="footer_top_content">
        <div id="footer_content_one">
        </div>
        <div id="footer_content_two">
        </div>
        <div id="footer_content_three">
        </div>
        <div id="footer_content_four">
        </div>
    </div>
    <div id="footer_bottom_content">
        <a style="text-decoration:none" href="https://designwebkit.com/wp-content/uploads/2017/09/Evolution.jpg"><h2 id="example_link">Example Footer</h2></a>
    </div>
</footer>

app/views/talents/create.html.erb
<div id = "title_create">
    <h3 id="tell_more"> TELL US MORE</h3>
    <h2> Select From Below That Matches Your Need</h2>
</div>

app/views/talents/index.html.erb
<h1><%= @talents.first.user_name %></h1>
<br><br>
<div id="talent_format_big_div">
    <div class="talent_lists_main_div">
        <div id="talent_lists_format_child_div">
            <% @talents.each do |talent| %>
                <div class="talent_lists_child_div">
                    <!-- <img class="talent_images" src="<%=talent.image %>"> -->
                    <img class="talent_images">
                    <div class="talent_lists"><%= talent.user_name %></div>
                    <div class="talent_lists"><%= talent.location %></div>
                    <div class="talent_lists"><%= talent.talent_offered %></div>
                </div>
            <% end %>
        </div>
    </div>

    <div class="talent_reviews_main_div">
        <% @talents.each do |talent| %>
            <div class="talent_reviews">
                <% talent.talent_reviews.each do |review| %>
                    <p><%= review.reviews %></p></p>
                <% end %>
            </div>
        <% end %>
    </div>
</div>   

app/views/talents/profile.html.erb
<div id="main_talent_profile_div">
    <div id="talent_profile_div_left">
        <h3 id="item_name">Mazarati</h3>
        <img id="item_image" src="https://www.maserati.com/mediaObject/sites/international/Brand/Alfieri/2016-05-24/Alfieri-9/resolutions/res-l1600x10000/Alfieri-9.jpg">
        <div id="item_description">
            <div id="item_description_head">
                <div id="item_head_image_div"><img id="item_head_image"></div>
                <h5 id="item_head_user"><span id="head_username_span">Anthony Thomas<span> <span id="head_date_span">–– 3 days ago</span></h5>
            </div>
            <div class="ui inverted divider"></div>
            <p style="line-height: 2em">Total amount of monthly payments is $32,724. Option to buy at lease end at pre-negotiated price. Dealer’s actual terms may vary. Offer through approved third party lessor and not Maserati North America, Inc. Residency restrictions apply. Must take retail delivery by January 31, 2019. $300 disposition fee due at lease end. See your participating local authorized Maserati Dealer for details.</p>
        </div>
    </div>
    <div id="talent_profile_div_right">
        <!--<h2 id="item_price">$120,000</h2>-->
        <h2 id="item_price">$120,000</h2>
        <button id="contact_dealer" class="ui twitter button">Contact Owner</button><br>
        <button id="add_favorite">Add to Favorites</button>
        <table id="product_faq_table">
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Condition</td>
                <td class="product_faq_table-column">Excellent</td>
            </tr>
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Cylinders</td>
                <td class="product_faq_table-column">8 Cyclinders</td>
            </tr>
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Drive</td>
                <td class="product_faq_table-column">Rwd </td>
            </tr>
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Fuel</td>
                <td class="product_faq_table-column">Gas</td>
            </tr>
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Odometer</td>
                <td class="product_faq_table-column">36,500</td>
            </tr>
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Paint</td>
                <td class="product_faq_table-column">Silver</td>
            </tr>
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Color</td>
                <td class="product_faq_table-column">Grey</td>
            </tr>
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Transmission</td>
                <td class="product_faq_table-column">Gear</td>
            </tr>
            <tr class="product_faq_table_row">
                <td class="product_faq_table-column">Type</td>
                <td class="product_faq_table-column">Coupe</td>
            </tr>
        </table>
        <div id="location_map">
            <iframe id="map_iframe" src="https://www.bing.com/maps/embed?h=250&w=250&cp=53.107871999999986~-2.487155000000001&lvl=14&typ=d&sty=r&src=SHELL&FORM=MBEDV8" scrolling="no">
            </iframe>
            <div id="marker_style">
                <a id="largeMapLink" target="_blank" href="https://www.bing.com/maps?cp=53.107871999999986~-2.487155000000001&amp;sty=r&amp;lvl=14&amp;FORM=MBEDLD">View Larger Map</a> &nbsp; | &nbsp;
                <a id="dirMapLink" target="_blank" href="https://www.bing.com/maps/directions?cp=53.107871999999986~-2.487155000000001&amp;sty=r&amp;lvl=14&amp;rtp=~pos.53.107871999999986_-2.487155000000001____&amp;FORM=MBEDLD">Get Directions</a>
            </div>
        </div>
    </div>
</div>

app/views/talents/search.html.erb
<br><br>
<div id="talent_format_big_div">
    <div class="talent_lists_main_div">
        <div id="talent_lists_format_child_div">
            <% @talents.each do |talent| %>
                <div class="talent_lists_child_div">
                    <!-- <img class="talent_images" src="<%=talent.image %>"> -->
                    <img class="talent_images">
                    <div class="talent_lists"><%= talent.user_name %></div>
                    <div class="talent_lists"><%= talent.location %></div>
                    <div class="talent_lists"><%= talent.talent_offered %></div>
                </div>
            <% end %>
        </div>
    </div>

    <div class="talent_reviews_main_div">
        <% @talents.each do |talent| %>
            <div class="talent_reviews">
                <% talent.talent_reviews.each do |review| %>
                    <p><%= review.reviews %></p></p>
                <% end %>
            </div>
        <% end %>
    </div>
</div>    

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/display.html.erb
<h1>Users#display</h1>
<p>Find me in app/views/users/display.html.erb</p>

app/views/users/index.html.erb
<h1> Users</h1>
<br><br>

<div id="talent_format_big_div">
    <div class="talent_lists_main_div">
        <div id="talent_lists_format_child_div">
            <% @talents.each do |talent| %>
                <div class="talent_lists_child_div">
                        <img class="talent_images">
                        <div class="talent_lists"><%= talent.user_name %></div>
                    <% talent.talent_reviews.reverse.each do |review| %>
                        <div class="talent_lists">
                            <p><%= review.reviews %></p>
                            <p>Reviewed by: <%= review.host.user_name %></p>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/replace.html.erb
<h1>Users#replace</h1>
<p>Find me in app/views/users/replace.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>